export const pathNames = {
	login: '/login',
	userManagement: '/',
	userDetail: '/detail',
	menusManagement: '/menus',
	menuDetail: '/menus/detail',
	ordersManagement: '/orders',
	orderDetail: '/orders/detail',
	popupsManagement: '/popups',
	popupDetail: '/popups/detail',
	bannersManagement: '/banners',
	bannerDetail: '/banners/detail',
	regionsManagement: '/regions',
	regionDetail: '/regions/detail',
};
